# Generated by Django 3.0.7 on 2023-03-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20230327_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='twitter_link',
            new_name='linkedin_profile',
        ),
    ]
