# Generated by Django 4.1.7 on 2023-04-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=4, max_length=10),
        ),
    ]
